name: DeepSource Test Coverage

on:
  push:
  pull_request:

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Jest
        run: npm install --save-dev jest

      - name: Run tests with Cobertura coverage
        run: npx jest --coverage=true --coverageReporters=cobertura --passWithNoTests

      - name: Install DeepSource CLI
        run: curl -fsSL https://cli.deepsource.com/install | BINDIR=./bin sh

      - name: Report test coverage to DeepSource
        run: ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ vars.DEEPSOURCE_DSN }}
